theme: jekyll-theme-minimal
title: SRP AM Prediction Challenge
author: SRP-AM Team
email: aahenri@sandia.gov
description: >
This page contains all the information needed to participate in the SRP AM Prediction Challenge.

show_excerpts: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      comments: true 
      share: true 
